// AUTOGENERATED: 45 cartas de decisión
export const decisionCards = [
  {
    "id": 101,
    "title": "SOS en la azotea",
    "text": "En un edificio de oficinas, una bengala roja ilumina la noche. Dos voces piden ayuda desde la azotea, pero la escalera está bloqueada por un enjambre de zombis. El humo atrae más criaturas y el tiempo corre. ¿Asumes el riesgo o proteges al grupo?",
    "choices": [
      {
        "text": "Forzar el rescate ahora",
        "effect": {
          "zombies": 3,
          "morale": 5,
          "survivors": 2,
          "ammo": -3
        }
      },
      {
        "text": "Esperar a que amanezca",
        "effect": {
          "morale": -2,
          "zombies": 1,
          "survivors": 1
        }
      },
      {
        "text": "Retirarse y marcar la zona",
        "effect": {
          "morale": -5,
          "karma": -3
        }
      }
    ]
  },
  {
    "id": 102,
    "title": "El camión frigorífico",
    "text": "Un camión frigorífico abandonado vibra con un generador aún en marcha. Dentro hay alimentos en buen estado, pero también golpes desde el compartimiento trasero. Un cerrojo asegura la puerta. ¿A quién beneficias primero: al grupo o a quien esté dentro?",
    "choices": [
      {
        "text": "Abrir y asistir",
        "effect": {
          "survivors": 1,
          "morale": 3,
          "zombies": 2
        }
      },
      {
        "text": "Cargar la comida y huir",
        "effect": {
          "food": 10,
          "morale": -4,
          "karma": -3
        }
      },
      {
        "text": "Intercambiar ayuda por información",
        "effect": {
          "food": 5,
          "morale": 1,
          "fuel": -1
        }
      }
    ]
  },
  {
    "id": 103,
    "title": "El hospital sin luz",
    "text": "El hospital municipal está a oscuras, sus pasillos huelen a cloro y miedo. Se rumorea que aún queda un quirófano funcional en el sótano. La entrada colapsada obliga a reptar por conductos estrechos. ¿Riesgas una incursión quirúrgica?",
    "choices": [
      {
        "text": "Buscar medicina en grupo",
        "effect": {
          "medicine": 6,
          "zombies": 3,
          "morale": 2
        }
      },
      {
        "text": "Enviar a un solo explorador",
        "effect": {
          "medicine": 3,
          "morale": -1,
          "casualties": "random"
        }
      },
      {
        "text": "Marcar y volver mejor preparados",
        "effect": {
          "materials": -2,
          "time": -1,
          "morale": 1
        }
      }
    ]
  },
  {
    "id": 104,
    "title": "La radio del coleccionista",
    "text": "Una voz en frecuencia corta ofrece coordenadas de un refugio a cambio de una reliquia: un viejo vinilo, una foto, un amuleto. El trueque duele porque arranca recuerdos. ¿Cuánto vale un símbolo cuando la vida depende de decisiones frías?",
    "choices": [
      {
        "text": "Entregar el objeto y seguir la señal",
        "effect": {
          "morale": -2,
          "fuel": -2,
          "mystery_solved": "maybe"
        }
      },
      {
        "text": "Negociar otro trato",
        "effect": {
          "charisma_check": true,
          "fuel": -1
        }
      },
      {
        "text": "Rechazar y mantener la memoria",
        "effect": {
          "morale": 3,
          "missed_opportunity": true
        }
      }
    ]
  },
  {
    "id": 105,
    "title": "Puente peatonal",
    "text": "El río divide la ciudad y el único paso seguro es un puente peatonal lleno de coches volcados. Al otro lado hay huertos comunitarios. Un rugido distante anuncia una horda. ¿Atravesar ahora o buscar un rodeo?",
    "choices": [
      {
        "text": "Cruzarlo en formación",
        "effect": {
          "zombies": 4,
          "food": 6,
          "morale": 2
        }
      },
      {
        "text": "Rodear por la ribera",
        "effect": {
          "time": -1,
          "energy": -3,
          "morale": 1
        }
      },
      {
        "text": "Construir una balsa improvisada",
        "effect": {
          "materials": -5,
          "risk": "high",
          "morale": 2
        }
      }
    ]
  },
  {
    "id": 106,
    "title": "El culto del andén",
    "text": "En la estación subterránea, un grupo ha hecho su hogar. Exigen ofrendas de comida a cambio de paso. Han mantenido el túnel seguro, pero su líder usa el miedo para controlar. ¿Pagar, enfrentar o persuadir?",
    "choices": [
      {
        "text": "Pagar el peaje",
        "effect": {
          "food": -4,
          "morale": -1,
          "safety": true
        }
      },
      {
        "text": "Enfrentar al líder",
        "effect": {
          "zombies": 2,
          "morale": -2,
          "potential_alliance": true
        }
      },
      {
        "text": "Persuadir por necesidad común",
        "effect": {
          "charisma_check": true,
          "materials": -2,
          "morale": 2
        }
      }
    ]
  },
  {
    "id": 107,
    "title": "La sirena que no cesa",
    "text": "Una alarma de fábrica suena cada hora. El eco atrae zombis y asusta a los niños. Dentro, un panel averiado chisporrotea. Cortar la energía dejaría la zona a oscuras. ¿Silencio con riesgo, o ruido que mantiene luz?",
    "choices": [
      {
        "text": "Cortar la electricidad",
        "effect": {
          "zombies": -1,
          "morale": -1,
          "materials": -1
        }
      },
      {
        "text": "Arreglar el panel",
        "effect": {
          "materials": -3,
          "morale": 3
        }
      },
      {
        "text": "Trasladar al grupo",
        "effect": {
          "fuel": -2,
          "morale": -2,
          "safety": true
        }
      }
    ]
  },
  {
    "id": 108,
    "title": "La escuela inundada",
    "text": "El gimnasio de una escuela se ha convertido en un espejo de agua turbia. Bajo los pupitres flotan mochilas y esperanzas. Los rumores dicen que hay un botiquín en la enfermería del segundo piso. El primer piso, sin embargo, está plagado.",
    "choices": [
      {
        "text": "Nadar por suministros",
        "effect": {
          "medicine": 4,
          "infection_risk": true,
          "morale": 1
        }
      },
      {
        "text": "Construir pasarelas",
        "effect": {
          "materials": -4,
          "time": -1,
          "zombies": -1
        }
      },
      {
        "text": "Abandonar la escuela",
        "effect": {
          "morale": -3
        }
      }
    ]
  },
  {
    "id": 109,
    "title": "Mercado nocturno",
    "text": "Un mercado clandestino florece entre contenedores. Venden agua purificada a precio absurdo y munición dudosa. La seguridad es una mezcla de códigos y miradas. ¿Comprar, robar o hacer aliados?",
    "choices": [
      {
        "text": "Comprar suministros críticos",
        "effect": {
          "water": 6,
          "ammo": 10,
          "materials": -3,
          "fuel": -2
        }
      },
      {
        "text": "Robar en la confusión",
        "effect": {
          "water": 3,
          "ammo": 5,
          "morale": -5,
          "karma": -5
        }
      },
      {
        "text": "Hacer un contacto",
        "effect": {
          "morale": 2,
          "potential_alliance": true,
          "time": -1
        }
      }
    ]
  },
  {
    "id": 110,
    "title": "El parque de caravanas",
    "text": "Caravanas desiertas guardan historias de partidas apresuradas. Una parece intacta, con marcas recientes de neumáticos. Un rastro de sangre se pierde hacia el bosque. ¿Rastrear, tomar lo útil o trancar puertas?",
    "choices": [
      {
        "text": "Rastrear al herido",
        "effect": {
          "survivors": 1,
          "medicine": 2,
          "zombies": 2
        }
      },
      {
        "text": "Saqueo rápido y salida",
        "effect": {
          "food": 4,
          "fuel": 3,
          "morale": -1
        }
      },
      {
        "text": "Asegurar una caravana como base",
        "effect": {
          "materials": -3,
          "defense": 2,
          "morale": 2
        }
      }
    ]
  },
  {
    "id": 111,
    "title": "La biblioteca en ruinas",
    "text": "Entre estanterías derrumbadas, aún huele a papel y tinta. Un archivo de mapas podría revelar rutas seguras, pero el techo amenaza con caer. Un murmullo de muertos llega desde el sótano.",
    "choices": [
      {
        "text": "Rescatar mapas y salir",
        "effect": {
          "materials": -1,
          "morale": 2,
          "zombies": 2
        }
      },
      {
        "text": "Solo revisar la planta baja",
        "effect": {
          "morale": 1,
          "time": -1
        }
      },
      {
        "text": "Sellar el sótano y marchar",
        "effect": {
          "materials": -2,
          "zombies": -2,
          "morale": -1
        }
      }
    ]
  },
  {
    "id": 112,
    "title": "Risas en el túnel",
    "text": "Un eco de risas infantiles suena en un túnel de servicio. Son grabaciones en bucle para atraer incautos. Al fondo, una caja fuerte abierta y una sombra inquieta.",
    "choices": [
      {
        "text": "Avanzar con sigilo",
        "effect": {
          "ammo": 2,
          "zombies": 2,
          "morale": 1
        }
      },
      {
        "text": "Retirarse y evitar la trampa",
        "effect": {
          "morale": -1
        }
      },
      {
        "text": "Colocar una contratrampa",
        "effect": {
          "materials": -3,
          "zombies": -1,
          "morale": 2
        }
      }
    ]
  },
  {
    "id": 113,
    "title": "Invernadero olvidado",
    "text": "Un invernadero comunitario ha sobrevivido al abandono. Algunas plantas dan frutas, otras están podridas y atraen moscas. El riego automático falla intermitente.",
    "choices": [
      {
        "text": "Cosecha rápida",
        "effect": {
          "food": 6,
          "morale": 2
        }
      },
      {
        "text": "Reparar riego",
        "effect": {
          "materials": -3,
          "food": 10,
          "time": -1
        }
      },
      {
        "text": "Tomar semillas para el campamento",
        "effect": {
          "materials": -1,
          "morale": 1,
          "food": 2
        }
      }
    ]
  },
  {
    "id": 114,
    "title": "Peaje en la autopista",
    "text": "Una barricada de coches cierra el paso. Tres personas armadas proponen intercambio justo, pero están nerviosas. Un disparo accidental podría desatar el caos.",
    "choices": [
      {
        "text": "Intercambio honesto",
        "effect": {
          "ammo": -2,
          "food": 5,
          "water": 4
        }
      },
      {
        "text": "Amenazar para pasar",
        "effect": {
          "morale": -4,
          "karma": -4,
          "zombies": 2
        }
      },
      {
        "text": "Invitarlos al campamento",
        "effect": {
          "survivors": 2,
          "morale": 3,
          "resources": -2
        }
      }
    ]
  },
  {
    "id": 115,
    "title": "La colmena",
    "text": "En una fábrica de textiles, los pasillos vibran como si tuvieran vida. Decenas de infectados duermen apilados, en aparente letargo. Un contenedor metálico destaca en el centro.",
    "choices": [
      {
        "text": "Robar y huir sin ruido",
        "effect": {
          "materials": 5,
          "ammo": 3
        }
      },
      {
        "text": "Destruir el nido",
        "effect": {
          "zombies": 6,
          "morale": 2
        }
      },
      {
        "text": "Marcar la zona para otros",
        "effect": {
          "morale": 1,
          "karma": 2
        }
      }
    ]
  },
  {
    "id": 116,
    "title": "Autobús escolar",
    "text": "Un bus amarillo yace cruzado en la calle. Dentro, dibujos infantiles y mochilas. Bajo un asiento, un maletín con candado y un mapa marcado con cruces.",
    "choices": [
      {
        "text": "Forzar el maletín",
        "effect": {
          "materials": -1,
          "medicine": 2,
          "morale": -1
        }
      },
      {
        "text": "Seguir el mapa",
        "effect": {
          "fuel": -2,
          "mystery_solved": "maybe",
          "zombies": 2
        }
      },
      {
        "text": "Llevar recuerdos al campamento",
        "effect": {
          "morale": 3
        }
      }
    ]
  },
  {
    "id": 117,
    "title": "Almacén municipal",
    "text": "Puertas metálicas resisten a medias. Se escucha el eco de latas y herramientas. Podrían haber materiales, o un refugio improvisado con ocupantes hostiles.",
    "choices": [
      {
        "text": "Entrar con protección",
        "effect": {
          "materials": 8,
          "zombies": 3
        }
      },
      {
        "text": "Vigilar y negociar",
        "effect": {
          "charisma_check": true,
          "materials": 4
        }
      },
      {
        "text": "Pasar de largo",
        "effect": {
          "morale": -1
        }
      }
    ]
  },
  {
    "id": 118,
    "title": "Azufre en el aire",
    "text": "Una fuga en tuberías industriales pinta el aire de un amarillo irritante. El lugar tiene combustible y filtros. Un error aquí se paga con tos y mareos.",
    "choices": [
      {
        "text": "Recoger combustible",
        "effect": {
          "fuel": 6,
          "morale": 1,
          "risk": "high"
        }
      },
      {
        "text": "Buscar filtros y máscaras",
        "effect": {
          "materials": 3,
          "morale": 2
        }
      },
      {
        "text": "Evitar la zona",
        "effect": {
          "morale": -1
        }
      }
    ]
  },
  {
    "id": 119,
    "title": "Santuario improvisado",
    "text": "Una biblioteca infantil convertida en santuario: mantas, velas, un cuaderno de nombres. Un perro viejo cuida la puerta. Hay cartas que piden que alguien avise a parientes.",
    "choices": [
      {
        "text": "Llevar cartas a destino",
        "effect": {
          "morale": 3,
          "fuel": -2
        }
      },
      {
        "text": "Adoptar al perro guardián",
        "effect": {
          "morale": 4
        }
      },
      {
        "text": "Tomar suministros y partir",
        "effect": {
          "food": 3,
          "medicine": 1,
          "morale": -1
        }
      }
    ]
  },
  {
    "id": 120,
    "title": "Antena en la loma",
    "text": "Una antena de radio sigue alimentada por paneles. Se pueden emitir mensajes de alcance regional. Comunicar implica exponerse; callar, quedarse aislados.",
    "choices": [
      {
        "text": "Emitir coordenadas seguras",
        "effect": {
          "morale": 3,
          "exposure_risk": true
        }
      },
      {
        "text": "Escanear frecuencias",
        "effect": {
          "time": -1,
          "mystery_solved": "maybe"
        }
      },
      {
        "text": "Apagar y desmontar paneles",
        "effect": {
          "materials": 3,
          "morale": -2
        }
      }
    ]
  },
  {
    "id": 121,
    "title": "Estación de policía",
    "text": "El vestíbulo está vacío, pero se oyen golpes sordos desde la armería. Expedientes abiertos cuentan historias de los primeros días del brote.",
    "choices": [
      {
        "text": "Forzar la armería",
        "effect": {
          "ammo": 12,
          "zombies": 3
        }
      },
      {
        "text": "Revisar expedientes",
        "effect": {
          "morale": 1,
          "knowledge_preserved": true
        }
      },
      {
        "text": "Sellar entradas",
        "effect": {
          "materials": -3,
          "defense": 2
        }
      }
    ]
  },
  {
    "id": 122,
    "title": "Teatro comunitario",
    "text": "Un escenario polvoriento, trajes, focos que aún funcionan con un generador. Un grupo quiere representar una obra para levantar la moral, otros temen el ruido.",
    "choices": [
      {
        "text": "Permitir la función",
        "effect": {
          "morale": 8,
          "zombie_attraction": true
        }
      },
      {
        "text": "Ensayo silencioso",
        "effect": {
          "morale": 4
        }
      },
      {
        "text": "Cancelar y mover recursos",
        "effect": {
          "materials": 2,
          "morale": -2
        }
      }
    ]
  },
  {
    "id": 123,
    "title": "Depósito de trenes",
    "text": "Vagones oxidados guardan cajas numeradas. Una locomotora parece reparable con las piezas correctas. Ponerla en marcha podría abrir rutas… o anunciar su posición.",
    "choices": [
      {
        "text": "Buscar piezas y reparar",
        "effect": {
          "materials": -6,
          "fuel": -3,
          "morale": 3
        }
      },
      {
        "text": "Saqueo selectivo",
        "effect": {
          "food": 4,
          "ammo": 6
        }
      },
      {
        "text": "Dejar todo intacto",
        "effect": {
          "morale": -1
        }
      }
    ]
  },
  {
    "id": 124,
    "title": "Callejón de espejos",
    "text": "Un callejón con escaparates rota la luz y confunde a los zombis. También refleja la fatiga en sus rostros. Atravesarlo ahorra tiempo, pero duele verlo.",
    "choices": [
      {
        "text": "Atravesar rápido",
        "effect": {
          "time": -1,
          "morale": -2
        }
      },
      {
        "text": "Evitar por avenida",
        "effect": {
          "energy": -3
        }
      },
      {
        "text": "Romper espejos críticos",
        "effect": {
          "materials": -1,
          "zombies": -1
        }
      }
    ]
  },
  {
    "id": 125,
    "title": "Caseta de peaje",
    "text": "Un anciano cobraba peaje antes del fin. Ahora custodia un cuaderno con nombres y deudas, y una caja con llaves de depósito. Dice que algunas llaves aún valen.",
    "choices": [
      {
        "text": "Pagar vieja deuda simbólica",
        "effect": {
          "morale": 3,
          "karma": 3
        }
      },
      {
        "text": "Tomar una llave y probar",
        "effect": {
          "materials": 2,
          "mystery_solved": "maybe"
        }
      },
      {
        "text": "Ignorarlo y seguir",
        "effect": {
          "morale": -1
        }
      }
    ]
  },
  {
    "id": 126,
    "title": "Campanas del barrio",
    "text": "Alguien cuelga campanas en balcones. Sonan con el viento y alertan a tiempo… y a veces a los muertos. El autor deja notas pidiendo respeto por el ruido nocturno.",
    "choices": [
      {
        "text": "Adoptar el sistema",
        "effect": {
          "materials": -2,
          "defense": 2
        }
      },
      {
        "text": "Quitarlas de nuestra ruta",
        "effect": {
          "morale": 1,
          "zombies": -1
        }
      },
      {
        "text": "Silenciarlas de noche",
        "effect": {
          "morale": 2,
          "zombie_attraction": -1
        }
      }
    ]
  },
  {
    "id": 127,
    "title": "Cueva del río",
    "text": "Una cueva cercana sirve como frigorífico natural. Hay huellas recientes de botas y sangre seca. Dentro, cajas con conservas y una mochila infantil.",
    "choices": [
      {
        "text": "Explorar a fondo",
        "effect": {
          "food": 8,
          "zombies": 3
        }
      },
      {
        "text": "Tomar lo esencial",
        "effect": {
          "food": 4,
          "morale": 1
        }
      },
      {
        "text": "Dejar una nota de aviso",
        "effect": {
          "morale": 2,
          "karma": 2
        }
      }
    ]
  },
  {
    "id": 128,
    "title": "Plaza de estatuas",
    "text": "Estatuas envueltas en lonas; alguien quiso protegerlas. Bajo una, un alijo de medicamentos y una carta de despedida. La autora pide que nadie la siga.",
    "choices": [
      {
        "text": "Tomar medicina y seguir",
        "effect": {
          "medicine": 5,
          "morale": 1
        }
      },
      {
        "text": "Buscar a la autora",
        "effect": {
          "survivors": 1,
          "zombies": 2
        }
      },
      {
        "text": "Respetar la petición",
        "effect": {
          "morale": 2
        }
      }
    ]
  },
  {
    "id": 129,
    "title": "Barrio amurallado",
    "text": "Vecinos han hecho una muralla de puertas y muebles. Dejan pasar solo a familias con niños. Ven a tu grupo con recelo y cansancio.",
    "choices": [
      {
        "text": "Donar comida por paso",
        "effect": {
          "food": -5,
          "morale": 2
        }
      },
      {
        "text": "Ofrecer guardias nocturnas",
        "effect": {
          "morale": 2,
          "defense": 1,
          "time": -1
        }
      },
      {
        "text": "Rodear en silencio",
        "effect": {
          "time": -1
        }
      }
    ]
  },
  {
    "id": 130,
    "title": "Gasolinera fantasma",
    "text": "Luces parpadean, surtidores secos, pero el sótano huele a combustible. El compresor está medio roto. Una sombra se mueve tras la caja registradora.",
    "choices": [
      {
        "text": "Bajar al sótano",
        "effect": {
          "fuel": 8,
          "zombies": 2
        }
      },
      {
        "text": "Desmontar piezas útiles",
        "effect": {
          "materials": 4
        }
      },
      {
        "text": "Salir sin ruido",
        "effect": {
          "morale": -1
        }
      }
    ]
  },
  {
    "id": 131,
    "title": "Río de barro",
    "text": "Lluvias recientes han convertido el sendero en lodo. Avanzar cansa el doble. A los lados, huertos abandonados prometen algo de alimento.",
    "choices": [
      {
        "text": "Empujar y seguir",
        "effect": {
          "energy": -4,
          "time": -1,
          "food": 2
        }
      },
      {
        "text": "Esperar a que seque",
        "effect": {
          "morale": -1
        }
      },
      {
        "text": "Buscar camino alterno",
        "effect": {
          "time": -1,
          "morale": 1
        }
      }
    ]
  },
  {
    "id": 132,
    "title": "El taller del relojero",
    "text": "Engranajes, aceites y precisión. El relojero dejó notas de mantenimiento que indican un refugio sincronizado con señales horarias. Encontrarlo exige paciencia.",
    "choices": [
      {
        "text": "Seguir las pistas",
        "effect": {
          "time": -1,
          "morale": 1,
          "mystery_solved": "maybe"
        }
      },
      {
        "text": "Tomar herramientas",
        "effect": {
          "materials": 3
        }
      },
      {
        "text": "Cerrar y marchar",
        "effect": {
          "morale": -1
        }
      }
    ]
  },
  {
    "id": 133,
    "title": "Cementerio colina arriba",
    "text": "Cruces improvisadas y flores de plástico. Un grupo realiza un ritual silencioso. Piden que nadie altere las tumbas. Alguien ha enterrado una caja sellada.",
    "choices": [
      {
        "text": "Respetar el lugar",
        "effect": {
          "morale": 2
        }
      },
      {
        "text": "Desenterrar la caja",
        "effect": {
          "medicine": 3,
          "morale": -3,
          "karma": -3
        }
      },
      {
        "text": "Pedir bendición para el grupo",
        "effect": {
          "morale": 3
        }
      }
    ]
  },
  {
    "id": 134,
    "title": "Muelle oxidado",
    "text": "Un bote de remos amarrado con cable y un cartel: 'No tocar'. A lo lejos, una isla con árboles altos. La corriente es caprichosa.",
    "choices": [
      {
        "text": "Cruzar al amanecer",
        "effect": {
          "fuel": -1,
          "morale": 2,
          "zombies": 1
        }
      },
      {
        "text": "Dejar el bote y rastrear",
        "effect": {
          "time": -1
        }
      },
      {
        "text": "Reforzar el bote",
        "effect": {
          "materials": -3,
          "safety": true
        }
      }
    ]
  },
  {
    "id": 135,
    "title": "La clínica vet",
    "text": "Jaulas, jeringas y ladridos demasiado silenciosos. Hay analgésicos y antibióticos de uso animal. Una puerta trasera abierta al callejón.",
    "choices": [
      {
        "text": "Recolectar medicinas",
        "effect": {
          "medicine": 4
        }
      },
      {
        "text": "Cerrar y asegurar",
        "effect": {
          "materials": -1,
          "defense": 1
        }
      },
      {
        "text": "Buscar dueños en el barrio",
        "effect": {
          "morale": 2,
          "time": -1
        }
      }
    ]
  },
  {
    "id": 136,
    "title": "Antiguo observatorio",
    "text": "Un domo roto apunta al cielo. Un cuaderno de observaciones contabiliza noches desde el brote. En la cúpula, latas de comida y baterías.",
    "choices": [
      {
        "text": "Tomar suministros",
        "effect": {
          "food": 4,
          "materials": 1
        }
      },
      {
        "text": "Anotar nuestra historia",
        "effect": {
          "morale": 2
        }
      },
      {
        "text": "Encender baliza una noche",
        "effect": {
          "exposure_risk": true,
          "morale": 3
        }
      }
    ]
  },
  {
    "id": 137,
    "title": "Aula de música",
    "text": "Instrumentos polvorientos y partituras. Una partitura reciente indica una melodía usada para coordinar turnos. Seguirla podría mejorar el ritmo del campamento.",
    "choices": [
      {
        "text": "Adoptar el sistema",
        "effect": {
          "morale": 3
        }
      },
      {
        "text": "Enseñar a los niños",
        "effect": {
          "morale": 4,
          "time": -1
        }
      },
      {
        "text": "Tomar cuerdas y madera",
        "effect": {
          "materials": 2
        }
      }
    ]
  },
  {
    "id": 138,
    "title": "Lavandería 24h",
    "text": "Secadoras aún tibias por un generador, olor a jabón. Hay ropa útil y mantas. Una ventana posterior ofrece fuga rápida.",
    "choices": [
      {
        "text": "Ropa y mantas para todos",
        "effect": {
          "morale": 3,
          "materials": 1
        }
      },
      {
        "text": "Repostar del generador",
        "effect": {
          "fuel": 3
        }
      },
      {
        "text": "Dejarlo como punto seguro",
        "effect": {
          "defense": 1,
          "time": -1
        }
      }
    ]
  },
  {
    "id": 139,
    "title": "Colegio técnico",
    "text": "Tornos, soldaduras y paneles desmontados. Hay estudiantes refugiados, desconfiados pero hábiles. Quieren piezas a cambio de ayudar.",
    "choices": [
      {
        "text": "Intercambiar piezas",
        "effect": {
          "materials": -4,
          "defense": 3
        }
      },
      {
        "text": "Ofrecer protección",
        "effect": {
          "survivors": 1,
          "morale": 2
        }
      },
      {
        "text": "Tomar prestado sin permiso",
        "effect": {
          "materials": 2,
          "morale": -3,
          "karma": -3
        }
      }
    ]
  },
  {
    "id": 140,
    "title": "Pasaje bajo el puente",
    "text": "Graffitis cuentan historias de resistencia. Un mural indica rutas de escape y zonas rojas. Un escondite con barritas de cereal.",
    "choices": [
      {
        "text": "Actualizar nuestros mapas",
        "effect": {
          "morale": 2
        }
      },
      {
        "text": "Tomar el escondite",
        "effect": {
          "food": 3
        }
      },
      {
        "text": "Añadir nuestras notas",
        "effect": {
          "morale": 2,
          "karma": 1
        }
      }
    ]
  },
  {
    "id": 141,
    "title": "Pequeño zoológico",
    "text": "Jaulas abiertas, olor fuerte. Algunos animales muertos, otros libres. Hay una caseta con tranquilizantes y equipo veterinario.",
    "choices": [
      {
        "text": "Recolectar tranquilizantes",
        "effect": {
          "medicine": 2,
          "zombies": -1
        }
      },
      {
        "text": "Rescatar animal guía",
        "effect": {
          "morale": 3
        }
      },
      {
        "text": "Cerrar accesos peligrosos",
        "effect": {
          "materials": -2,
          "defense": 1
        }
      }
    ]
  },
  {
    "id": 142,
    "title": "Tienda de camping",
    "text": "Mochilas, filtros de agua, cuerdas. El escaparate está roto, pero el almacén trasero tiene candado. Se oyen pasos arriba.",
    "choices": [
      {
        "text": "Forzar almacén",
        "effect": {
          "materials": 3,
          "water": 3,
          "zombies": 2
        }
      },
      {
        "text": "Tomar lo visible y salir",
        "effect": {
          "materials": 1,
          "water": 1
        }
      },
      {
        "text": "Asegurar la tienda",
        "effect": {
          "defense": 1,
          "morale": 1
        }
      }
    ]
  },
  {
    "id": 143,
    "title": "Faro de carretera",
    "text": "Un viejo faro de tráfico parpadea intermitente. Sirve de guía a viajeros… y a depredadores. Un cuaderno contiene mensajes de paso.",
    "choices": [
      {
        "text": "Dejar un mensaje",
        "effect": {
          "morale": 2
        }
      },
      {
        "text": "Apagar el faro",
        "effect": {
          "zombie_attraction": -1,
          "morale": -1
        }
      },
      {
        "text": "Fortificar el lugar",
        "effect": {
          "materials": -3,
          "defense": 2
        }
      }
    ]
  },
  {
    "id": 144,
    "title": "Panadería cerrada",
    "text": "Harina en el aire, hornos fríos. Hay levadura, latas y herramientas. Una puerta al sótano emana calor.",
    "choices": [
      {
        "text": "Encender un horno una vez",
        "effect": {
          "morale": 4,
          "zombie_attraction": true
        }
      },
      {
        "text": "Tomar víveres",
        "effect": {
          "food": 4
        }
      },
      {
        "text": "Cerrar todo herméticamente",
        "effect": {
          "materials": -2,
          "defense": 1
        }
      }
    ]
  },
  {
    "id": 145,
    "title": "Mirador del cerro",
    "text": "Desde lo alto se ve el patrón de las hordas. El viento corta, pero aquí arriba hay perspectiva y paz. Una antena rota podría servir de repuesto.",
    "choices": [
      {
        "text": "Observar patrones",
        "effect": {
          "morale": 2,
          "zombies": -1
        }
      },
      {
        "text": "Bajar con repuesto",
        "effect": {
          "materials": 2
        }
      },
      {
        "text": "Dejar señal de humo breve",
        "effect": {
          "exposure_risk": true,
          "morale": 2
        }
      }
    ]
  }
];
